version: "3"

services:
  mysql:
    image: mysql:8.0.33
    platform: linux/arm64
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "txwithr2dbc"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 0.5s
      retries: 5

  wiremock:
    image: wiremock/wiremock:2.35.0
    platform: linux/arm64
    ports:
      - "9561:9561"
    volumes:
      - ./.docker/wiremock:/home/wiremock
    command: -port 9561 --local-response-templating --verbose